# Análisis Exploratorio de Datos - Campañas de Marketing Bancario

El objetivo de este proyecto es analizar los datos de campañas de marketing de una entidad bancaria para identificar patrones y factores que influyen en la contratación de productos.

1. IMPORTACIÓN DE LIBRERÍAS

Primero, instalar pandas (y openpyxl), matplotlib y seaborn en la terminal con pip install, luego importar las librerías necesarias:

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

2. CARGA DE DATOS

In [17]:
df = pd.read_csv("../data/RAW/bank-additional.csv")
excel = pd.ExcelFile("../data/RAW/customer-details.xlsx")

df1 = pd.read_excel(excel, sheet_name=0)
df2 = pd.read_excel(excel, sheet_name=1)
df3 = pd.read_excel(excel, sheet_name=2)

df_clientes = pd.concat([df1, df2, df3])

3. EXPLORACIÓN INICIAL

En este apartado, el objetivo es tener una imágen clara sobre la BBDD, sus columnas, valores y formatos, para poder realizar la limpieza correspondiente. Para ello, usamos funcionemos como head, info, describe. En este punto, también podemos detectar la cantidad de nulos por columna con los que vamos a trabajar, y así determinar el tratamiento que se le dará a cada uno.

In [18]:
df.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  object
 16  cons.conf.idx   43000 non-null  object
 17  euribor3m       33744 non-null  object
 18  nr.employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  object
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: float64(7), int64(5), object(12)
memory usage: 7.9+ MB

In [20]:
df.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [21]:
df.isnull().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

4. LIMPIEZA INICIAL

Cuando ya tenemos claro los valores con los que trabajamos, nos centramos en que cada uno tenga el formato correspondiente y eliminamos las columnas que no aporten al análisis.

In [22]:
# Eliminar la columna "Unnamed: 0", índice innecesario
df = df.drop(columns=["Unnamed: 0"])

In [23]:
# Convertir la variable objetivo "y" a numérica, donde "yes" se convierte en 1 y "no" en 0 para facilitar el análisis.
df["y"] = df["y"].map({"yes": 1, "no": 0})

In [ ]:
# Convertir los valores de las columnas numéricas a tipo numérico, ya que al leer el CSV se interpretaron como objetos (strings)
PENDIENTE

In [24]:
# Convertir la columna "date" a formato datetime, primero traduciendo los meses del español al inglés para que pandas pueda interpretarlos correctamente.
meses = {
    'enero': 'Jan', 'febrero': 'Feb', 'marzo': 'Mar', 'abril': 'Apr',
    'mayo': 'May', 'junio': 'Jun', 'julio': 'Jul', 'agosto': 'Aug',
    'septiembre': 'Sep', 'octubre': 'Oct', 'noviembre': 'Nov', 'diciembre': 'Dec'
}

df['date_en'] = df['date']
for es, en in meses.items():
    df['date_en'] = df['date_en'].str.replace(es, en, regex=True)

df['date'] = pd.to_datetime(df['date_en'], dayfirst=True)

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.day_name()

df.drop(columns=['date_en'], inplace=True)

5. MANEJO DE VALORES NULOS Y OUTLIERS

Para terminar con la limpieza de la tabla, es necesario tomar decisiones sobre el manejo de los valores nulos y outliers, ya que el correcto manejo de estos es escenial para el podterior análisis de los mismos.

In [25]:
df['age'].fillna(df['age'].median(), inplace=True)
df['education'].fillna('unknown', inplace=True)
df["job"].fillna(df["job"].mode()[0], inplace=True)

C:\Users\rscon\AppData\Local\Temp\ipykernel_15028\3000145775.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
C:\Users\rscon\AppData\Local\Temp\ipykernel_15028\3000145775.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['education'].fillna('unknown', inplace=True)
C:\Users\rscon\AppData\Local\Temp\ipykernel_15028\3000145775.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["job"].fillna(df["job"].mode()[0], inplace=True)

In [ ]:
#Comprobamos los nulos después de la limpieza

df.isnull().sum()

age                  0
job                  0
marital             85
education            0
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
year               248
month              248
day                248
weekday            248
dtype: int64